### PR TITLE
GRUB Plugin

### PR DESCRIPTION
**Pull request by johnramsden**
# GRUB Plugin

I've started work on a plug-in for grub. In my limited testing in a virtual machine, it currently is able to create boot entries for whichever entry it's activating, but I don't have a way to have an entry for every existing boot environment. 

I'm considering having a separate file in `/etc/grub.d` for every current existing boot environment, but I'm not sure if it would be better to try and do it anymore programmatic way using grub's ability to generate and entries.

## Roadmap

- [x] Entry for active boot environment
- [ ] Entry for every boot environment

### CODE REVIEW

**Comment by johnramsden** [comment]
@zdykstra has been collaborating with me over email, helping with brainstorming and testing. For continuity here are his comments.

> Nice! I've been mulling over this problem the last few days, and I think 
> I have a reasonable compromise. On most systems I've used, grub.cfg is 
> generated via grub-mkconfig (or a wrapper on top of that), which uses 
> defaults in /etc/default/grub and then generator scripts in 
> /etc/grub.d/. It seems that simply extending these shell scripts to 
> handle two different cases could take care of creating 
> /boot/grub/grub.cfg for people. I'll attach a link to the generator 
> scripts, my /etc/default/grub, and my generated /boot/grub/grub.cfg so 
> that you can see what I'm talking about.
> 
> (grub.cfg)
> 
> It looks like in this case of zedenv, 00_header could be retained, and 
> then 10_linux could be modified and replaced with 10_zedenv_current, and 
> then 20_zedenv_alternate could be created.
> 
> - For 10_zedenv_current, the bootfs property would need to be 
> determined, and then the internal loop used to iterate kernels would 
> simply need to walk the /boot/<environment> directory. This is virtually 
> identical to what 10_linux does now.
> 
> - For 20_zedenv_alternate, bootfs would once again be read and then that 
> directory excluded from the list. An outer loop could be added which 
> feeds the inner loop with /boot/<environment> directories in whatever 
> shell glob order is preferred.
> 
> In both cases, all grub templating, /etc/default/grub values, etc would 
> be retained. This would also have the added benefit of producing a sane 
> and valid grub.cfg when the OS's packaging system calls grub-mkconfig -o 
> /boot/grub/grub.cfg on a kernel upgrade. This solves the issue of 
> needing to re-create grub.cfg on a kernel upgrade outside of the package 
> manager's process.
> 
> Any time then zedenv creates/promotes/demotes/destroys a boot 
> environment, it manages /boot/<environment> and the bindmount entry in 
> /etc/fstab, and then simply calls grub-mkconfig -o /boot/grub/grub.cfg 
> and a config is automagically inserted for our use.
> 
> There is the lingering question of exactly how the bindmounts work, 
> though. Below is listing of /boot on my system.
> 
> 
> 
> If /boot/default-1/ was bind-mounted to /boot, /boot/grub would still 
> need to actually exist there, as grub's loader code has to find 
> /boot/grub/grub.cfg and friends exactly there.
> 
> Let me know your thoughts on this. I'm not sure how shipping two scripts 
> based on 10_linux would work regarding liscensing.

**Comment by johnramsden** [comment]
@zdykstra commented:

> I've poked at this a bit more. And while /etc/grub.d is essentially 
> hard-coded in grub-mkconfig, it's easy to cheat and override. The 
> variable 'grub_mkconfig_dir' is set at the start of grub-mkconfig, 
> followed by /etc/default/grub being sourced. I was able to override the 
> variable there and point grub-mkconfig to /etc/zedenv.d/ as a test. It 
> then successfully generated this configuration file:
> [grub.cfg](https://github.com/johnramsden/zedenv/files/2065507/grub.cfg.txt)
> 
> ```
> # grep zedenv /etc/default/grub
> grub_mkconfig_dir="/etc/zedenv.d/"
> ```
> 
> I've confirmed that this is also present on Ubuntu 16.04, so this 
> appears to be a standard upstream GRUB script. So creating a custom 
> generator script directory with cloned(?) files from upstream GRUB looks 
> like it could integrate very nicely.

**Comment by johnramsden** [comment]
I didn't realize the generators could do so much. I think the idea of having either a custom directory for grub config is not a bad idea. Maybe It should end up being `/etc/zedenv/grub.d` go in case we end up needing some sort of other configuration and a configuration directory that's not grub related. Either that or a custom script in `/etc/grub.d`. However, the benefit of using grub's system directory is people know where to put configuration for it already and it will be correctly sourced if they put it there.

---

Regarding whether or not to use bind mounts. The question is with grub do we need them at all? Because if the kernels are stored on ZFS, each boot environment will just have its own correct kernel, so directories with every different type of kernel probably wouldn't be necessary.

I referenced my kernels on ZFS in this format on my test for dataset `vault/ROOT/default:`

```
linux /ROOT/default/@/boot/vmlinuz-linux zfs=vault/ROOT/default rw 
initrd /ROOT/default/@/boot/initramfs-linux.img
```

**Comment by johnramsden** [comment]
@zdykstra commented:

> My reasoning behind using a custom `grub.d` directory is that it allows 
> people to easily bypass the default `grub.d` generators with out actually 
> removing them from disk. This ensures that any grub package upgrades 
> will not need to re-populate `/etc/grub.d/`. The end result then is that 
> this allows for a very clean `/boot/grub/grub.cfg`. When zedenv installs 
> itself, it could create `/etc/zedenv/grub.d/` with the appropriate files 
> there, and maybe even append the appropriate entry to `/etc/default/grub `
> (or remind people to do it).
> 
> I think for this to be future proof with grub, it will need to manage 
> environments on /boot. It sounds like the grub upstream maintainers have 
> no desire to add any more ZFS features to grub, which means grub will 
> never support native zpool encryption. 
> https://github.com/zfsonlinux/zfs/issues/7153 Now, I could be an 
> outlier here in using grub on an ext4 `/boot` to handle booting a zpool, 
> but I suspect that this type of configuration will still be used for a 
> few years to come.
> 
> If you don't want to modify `grub.cfg` for non-active boot environments, 
> but just update/build for the active one, the following rough flow could 
> work:
> 
> ```
> ENV=`zedenv --list-active-environment`
> mount --bind /mnt/boot/ENV/ /boot
> 
> grub-mkconfig -o /boot/grub/grub.cfg
> cp -Rp /boot/grub/ /mnt/boot/grub/
> ```
> 
> `grub-mkconfig` would then use one or more custom generators to determine 
> the active environment and all the rest and build entries for them 
> accordingly.

**Comment by zdykstra** [comment]
Thanks for migrating the conversation to GitHub - you wrote the initial version far faster than I anticipated!

**Comment by zdykstra** [comment]
Let me know how you'd like to proceed on this - I can test and/or start creating grub.d generator scripts - license questions not withstanding.

**Comment by johnramsden** [comment]
That's too bad about grub not wanting to support any new ZFS features. I guess maybe the best option would be to support multiple boot environments with multiple directories containing kernels like done with systemd-boot https://github.com/johnramsden/zedenv/blob/6c3ea69227b2b925e7ea722847326a1683309dbe/zedenv/plugins/systemdboot.py#L251-L286

But maybe also support keeping kernels on ZFS, because I know there are people who use GRUB for specifically that purpose.

**Comment by zdykstra** [comment]
Good call - there's no one-size-fits-all solution here. Do you want to automatically detect what /boot is, and manage accordingly, or set it as a property of the zpool? 

I'm spinning up a new VM so that I can test with easy recovery options.

**Comment by johnramsden** [comment]
That's a good question about the grub scripts. I guess we could either rewrite the generator script in python, or just rewrite them from scratch in shell script. 

I don't really like the idea of merging in GNU code, that might cause licensing issues.

The actual part that is ZFS related is only really the following:

```shell
case x"$GRUB_FS" in
    xbtrfs)
	rootsubvol="`make_system_path_relative_to_its_root /`"
	rootsubvol="${rootsubvol#/}"
	if [ "x${rootsubvol}" != x ]; then
	    GRUB_CMDLINE_LINUX="rootflags=subvol=${rootsubvol} ${GRUB_CMDLINE_LINUX}"
	fi;;
    xzfs)
	rpool=`${grub_probe} --device ${GRUB_DEVICE} --target=fs_label 2>/dev/null || true`
	bootfs="`make_system_path_relative_to_its_root / | sed -e "s,@$,,"`"
	if [ -z "${rpool}" ]; then
		rpool=$(zfs list -Ho name -t filesystem | grep -m1 "${bootfs}$" | sed 's/\/.*//')
	fi
	LINUX_ROOT_DEVICE="ZFS=${rpool}${bootfs}"
	;;
esac
```

Would you be comfortable with rewriting what we need as a new shell script? Alternatively we forgo with the generator completely and do it all in the plugin... We can then call out to whichever GRUB programs we need such as `${grub_probe}`.

**Comment by johnramsden** [comment]
What I've done so far is used a default location if it's not set as a property on the dataset. https://github.com/johnramsden/zedenv/blob/fce5fcd1635f66dfa0212485fda9c38ab392c309/zedenv/plugins/grub.py#L66-L74

Maybe we should just default to `/boot`, and if someone has set `org.zedenv:grubboot`, we use that.

**Comment by johnramsden** [comment]
Another option is we could keep the GRUB plugin as a separate project, with the current generators cloned, meaning we wouldn't have to worry about licensing.

**Comment by zdykstra** [comment]
I'll start running through the various proposed solutions on my dev VMs to see how they start to flesh out in practice.

**Comment by johnramsden** [comment]
Moved some functionality from systemd-boot plugin, to the general Plugin class that was used for modifying the fstab https://github.com/johnramsden/zedenv/blob/f1721be772252d77cc5269a0e1711c95610b4d1e/zedenv/plugins/configuration.py#L120

Now it can be easily reused by other plugins, ie GRUB, to setup bindmounts.

---

Should hopefully get alternate mounts, with multiple directories functional tomorrow.

**Comment by zdykstra** [comment]
With surprisingly minimal changes to 10_linux, I have it generating grub.cfg for the active boot environment.

```
$ zedenv list
Name          Active   Mountpoint   Creation             
default       NR       /            Sun-Jun-3-11:37-2018 
test-1                 -            Sun-Jun-3-13:33-2018 
test-2                 -            Sun-Jun-3-13:33-2018 
upgrade-test           -            Sun-Jun-3-13:33-2018

```
```
### BEGIN /home/zdykstra/source/zedenv/grub.d/10_linux ###
menuentry 'Void GNU/Linux' --class void --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-/dev/vda' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod ext2
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root  f1317c9f-91c8-424d-826a-f42e44a54a48
	else
	  search --no-floppy --fs-uuid --set=root f1317c9f-91c8-424d-826a-f42e44a54a48
	fi
	echo	'Loading Linux 4.16.12_1 ...'
	linux	/default/vmlinuz-4.16.12_1 root=ZFS=locker/ROOT/default ro  loglevel=4 slub_debug=P page_poison=1
	echo	'Loading initial ramdisk ...'
	initrd	/default/initramfs-4.16.12_1.img
}
```

If /boot resides on a zpool, 10_linux is also able to build correct grub entries, assuming that a /boot/<environment/ directory structure is in use.

**Comment by johnramsden** [comment]
Nice! So does that generate an entry for the active boot environment even when it's not the current root file system?

What did you have to modify?

**Comment by zdykstra** [comment]
https://github.com/zdykstra/zedenv/commit/889ca5abccc06e77a7f2bcb6f5c0da9abee792c8

_zedenv-stub pool_ is a static tool to return the pool that we should check the bootfs value for. 

```
+ LINUX_ROOT_DEVICE=/dev/vda
+ /home/zdykstra/source/zedenv-generators/bin/zedenv-stub pool
+ rpool=locker
+ zpool get -Ho value bootfs locker
+ bootfs=locker/ROOT/default
+ basename locker/ROOT/default
+ bootenv=default
+ LINUX_ROOT_DEVICE=ZFS=locker/ROOT/default
```
That's the set -x trace for the start of the modified 10_linux. I'm open to suggestions on what sources should be checked for the data, but we do need to either determine the zpool and go from there, or have zedenv feed us the full data some how.

The commit message has a few more sample invocations.

**Comment by johnramsden** [comment]
That looks great, to get the pool you can just use:

```
mount | awk '/ \/ / {print $1}' | awk -F / '{print $1}'
```

Essentially get the root file system pool, and using `/` as the field delimiter, get the first field which is the pool name.

---

Regarding what to do about including the script, I have figured out how to make the plugins external, so that they could just be installed as a separate package and `zedenv` would notice them. 

It seems like the GRUB generator is doing a fair amount of other stuff that I don't quite understand, so trying to rewrite the generator as a python script might prove difficult without spending some time looking at everything the generator needs to do. If you still think the best course of action would be to just make a few changes to `10_linux`, and include it with the GRUB plug-in, what i'll do is just have the GRUB plugin be separate from the rest of the code base, meaning it can retain the GPL license.

**Comment by johnramsden** [comment]
@zdykstra I made some changes I thought might work on https://github.com/zdykstra/zedenv/pull/1, and sent you a pr, let me know what you think. 

Afterwards, it might make sense for you to fork [johnramsden/zedenv-grub](https://github.com/johnramsden/zedenv-grub), and we can continue planning there. I've removed all the code that's unrelated to the plugin.

**Comment by zdykstra** [comment]
Those changes look good to me. There's still a question about how kernel/initramfs management should be done when ZFS is backing /boot. Right now that generator always assumes there's a /boot/env- structure, which probably doesn't make as much sense for ZFS /boot.

**Comment by zdykstra** [comment]
Do you want to drag the relevant files in my PR over to the new project and development can continue there?

**Comment by johnramsden** [comment]
Yeah I've been thinking about that. I think I think what makes the most sense would be to use an alternate location for the kernels, and then bindmount each of them to `/boot`, like what was done with systemd-boot. Maybe we should use `/mnt/boot/env/zedenv-<boot env>` by default?

I'll also add a new flag to enable boot on ZFS, which we can set to no by default.

Going to go ahead and close this, and reopen it on the new repo https://github.com/johnramsden/zedenv-grub/pull/1

**Pull request closed without merging**
